disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - function_body_length
  - function_parameter_count 
  - todo
  - force_cast
  - force_try
  - mark
  - trailing_comma
  - identifier_name
  - large_tuple
  - unused_closure_parameter
  - multiple_closures_with_trailing_closure
  - opening_brace
  - nesting
  - type_name
  - cyclomatic_complexity
included: # paths to include during linting. `--path` is ignored if present.
  - Stage1st
  - Vendors
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
identifier_name:
  min_length: 2 # only min_length to make ID valid
cyclomatic_complexity:
  warning: 25
  error: 25
